[features]
seeds = false
skip-lint = false
[programs.devnet]
minterplace_program = "DzgHfmRkctH9W7d65vgxNPra2UqjWACBGZY1kFPMRy13"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/last_vondert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
